### ISSUE TITLE
Add support for ARM Flex shape

### ISSUE THREAD

**Issue by hyder** [oracle-terraform-modules/terraform-oci-operator#30]
ARM is now generally available on OCI: https://blogs.oracle.com/cloud-infrastructure/announcing-gitlab-arm-runner-support-for-the-arm-compute-platform-on-oracle-cloud-infrastructure

We need to add support for ARM shape

**Comment by kral2** [comment]
code in [oracle-terraform-modules/compute-instance](https://registry.terraform.io/modules/oracle-terraform-modules/compute-instance/oci/latest) supports it.
